# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c6b2502135b930ed06fb6218c7a3c9448b41f157c58790272ac0e2b1c6d5890e0557e6a6f8a566ea534cf191004245eb64a37cf2eb43e86b3234a62cf7852423

test:
  secret_key_base: 3039fa3c05589d273ac9effdb60e0fdc9c110d12fef99b8df49c2e656af70b4b5df88bb5f73258fc5b62ce464fe730baf3f71c508d9ae16be5b703b3ee161132

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
